# Generated by Django 3.2 on 2021-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
